//
//  BrowseGIFsModels.swift
//  GIPHYApp
//
//  Created by Daniel Ilchishyn on 11/2/17.
//  Copyright (c) 2017 KRUBERLICK. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import ObjectMapper

enum BrowseGIFs {
    enum FetchGIFs {
        struct Request {
            let query: String
        }

        struct Response: ImmutableMappable {
            let results: [GIF]

            init(map: Map) throws {
                results = (try? map.value("data")) ?? []
            }
        }

        struct ViewModel {
            let url: URL?
            let localGIFData: Data?
        }
    }

    enum Something {
        struct Request {

        }

        struct Response {

        }

        struct ViewModel {
            
        }
    }
}
