//
//  BrowseGIFsModels.swift
//  GIPHYApp
//
//  Created by Daniel Ilchishyn on 11/2/17.
//  Copyright (c) 2017 KRUBERLICK. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import ObjectMapper
import IGListKit

enum BrowseGIFs {
    enum FetchGIFs {
        struct Request {
            let query: String
        }

        struct Response {
            let data: [GIF]
        }

        struct ViewModel {
            class Item: ListDiffable {
                let gif: GIF

                init(gif: GIF) {
                    self.gif = gif
                }

                func diffIdentifier() -> NSObjectProtocol {
                    return gif.id as NSString
                }

                func isEqual(toDiffableObject object: ListDiffable?) -> Bool {
                    guard let object = object as? Item else {
                        return false
                    }

                    return object.gif == self.gif// && object.gif.localURL == self.gif.localURL
                }
            }

            let displayedItems: [Item]
        }
    }

    enum Something {
        struct Request {

        }

        struct Response {

        }

        struct ViewModel {
            
        }
    }
}
