//
//  BrowseGIFsInteractor.swift
//  GIPHYApp
//
//  Created by Daniel Ilchishyn on 11/2/17.
//  Copyright (c) 2017 KRUBERLICK. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BrowseGIFsBusinessLogic {
//    func reloadFeed()
//    func requestNextChunk()
//    func doSomething(request: BrowseGIFs.Something.Request)
}

protocol BrowseGIFsDataStore {
    //var name: String { get set }
}

class BrowseGIFsInteractor: BrowseGIFsBusinessLogic, BrowseGIFsDataStore {
    var presenter: BrowseGIFsPresentationLogic?
    var worker: BrowseGIFsWorker?
    //var name: String = ""
    
    // MARK: Do something
    
//    func doSomething(request: BrowseGIFs.Something.Request) {
//        worker = BrowseGIFsWorker()
//        worker?.doSomeWork()
//        
//        let response = BrowseGIFs.Something.Response()
//        presenter?.presentSomething(response: response)
//    }
}
