//
//  BrowseGIFsRouter.swift
//  GIPHYApp
//
//  Created by Daniel Ilchishyn on 11/2/17.
//  Copyright (c) 2017 KRUBERLICK. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol BrowseGIFsRoutingLogic {
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol BrowseGIFsDataPassing {
    var dataStore: BrowseGIFsDataStore? { get }
}

class BrowseGIFsRouter: NSObject, BrowseGIFsRoutingLogic, BrowseGIFsDataPassing {
    weak var viewController: BrowseGIFsViewController?
    var dataStore: BrowseGIFsDataStore?
    
    // MARK: Routing
    
    @objc func routeToViewGIF(segue: UIStoryboardSegue?) {
        if let segue = segue {
            let destinationVC = segue.destination as! ViewGIFViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToViewGIF(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "ViewGIFViewController") as! ViewGIFViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToViewGIF(source: dataStore!, destination: &destinationDS)
            navigateToViewGIF(source: viewController!, destination: destinationVC)
        }
    }
    
    // MARK: Navigation
    
    func navigateToViewGIF(source: BrowseGIFsViewController, destination: ViewGIFViewController) {
        source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    func passDataToViewGIF(source: BrowseGIFsDataStore, destination: inout ViewGIFDataStore) {
        destination.gif = ViewGIF.DisplayGIF.ViewModel(gif: source.selectedGIF.gif)
    }
    
    //func passDataToSomewhere(source: BrowseGIFsDataStore, destination: inout SomewhereDataStore)
    //{
    //  destination.name = source.name
    //}
}
