//
//  BrowseGIFsPresenter.swift
//  GIPHYApp
//
//  Created by Daniel Ilchishyn on 11/2/17.
//  Copyright (c) 2017 KRUBERLICK. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BrowseGIFsPresentationLogic {
    func presentSomething(response: BrowseGIFs.Something.Response)
}

class BrowseGIFsPresenter: BrowseGIFsPresentationLogic {
    weak var viewController: BrowseGIFsDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: BrowseGIFs.Something.Response) {
        let viewModel = BrowseGIFs.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
