//
//  BrowseGIFsPresenter.swift
//  GIPHYApp
//
//  Created by Daniel Ilchishyn on 11/2/17.
//  Copyright (c) 2017 KRUBERLICK. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BrowseGIFsPresentationLogic {
    func displayFetchedGIFs(response: BrowseGIFs.FetchGIFs.Response)
}

class BrowseGIFsPresenter: BrowseGIFsPresentationLogic {
    weak var viewController: BrowseGIFsDisplayLogic?
    
    // MARK: Do something
    
    func displayFetchedGIFs(response: BrowseGIFs.FetchGIFs.Response) {
        let viewModel = BrowseGIFs.FetchGIFs.ViewModel(displayedItems: response.data.map { BrowseGIFs.FetchGIFs.ViewModel.Item(gif: $0) })
        viewController?.displayFetchedGIFs(viewModel: viewModel)
    }
}
