//
//  ViewGIFInteractor.swift
//  GIPHYApp
//
//  Created by Daniel Ilchishyn on 11/2/17.
//  Copyright (c) 2017 KRUBERLICK. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ViewGIFBusinessLogic {
    func doSomething(request: ViewGIF.Something.Request)
}

protocol ViewGIFDataStore {
    //var name: String { get set }
}

class ViewGIFInteractor: ViewGIFBusinessLogic, ViewGIFDataStore {
    var presenter: ViewGIFPresentationLogic?
    var worker: ViewGIFWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: ViewGIF.Something.Request) {
        worker = ViewGIFWorker()
        worker?.doSomeWork()
        
        let response = ViewGIF.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
